name: Full Build, Push and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: [self-hosted, splitzy]
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'UI/**'
            backend:
              - 'backend/**'

  build_api:
    needs: changes
    if: |
      github.event_name == 'workflow_dispatch' ||
      needs.changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build_ui:
    needs: changes
    if: |
      github.event_name == 'workflow_dispatch' ||
      needs.changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy_final:
    needs: [build_api, build_ui]
    if: |
      always() &&
      (
        github.event_name == 'workflow_dispatch' ||
        needs.build_api.result != 'skipped' ||
        needs.build_ui.result != 'skipped'
      )
    uses: ./.github/workflows/deploy.yml
    secrets:
      APP_SETTINGS: ${{ secrets.APP_SETTINGS }}
