name: Build & Push Frontend Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, splitzy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version (date + run number)
        run: |
          DATE=$(date -u +'%Y.%m.%d')
          VERSION=$DATE-${{ github.run_number }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Frontend Docker image
        run: |
          docker build \
            -t rghvgrv/splitzy-ui:latest \
            -t rghvgrv/splitzy-ui:${VERSION} \
            UI

      - name: Push Frontend Docker image
        run: |
          docker push rghvgrv/splitzy-ui:latest
          docker push rghvgrv/splitzy-ui:${VERSION}

      - name: Cleanup old Frontend images (keep last 2)
        run: |
          TOKEN=$(curl -s -X POST https://hub.docker.com/v2/users/login/ \
            -H "Content-Type: application/json" \
            -d '{"username": "'${{ secrets.DOCKERHUB_USERNAME }}'", "password": "'${{ secrets.DOCKERHUB_TOKEN }}'"}' \
            | jq -r .token)

          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/rghvgrv/splitzy-ui/tags?page_size=100" \
            -H "Authorization: JWT $TOKEN" \
            | jq -r '.results | sort_by(.last_updated) | reverse | .[2:] | .[].name')

          for TAG in $TAGS; do
            if [ "$TAG" != "latest" ]; then
              echo "Deleting tag: $TAG"
              curl -s -X DELETE \
                "https://hub.docker.com/v2/repositories/rghvgrv/splitzy-ui/tags/$TAG/" \
                -H "Authorization: JWT $TOKEN"
            fi
          done
